site_title: Acosys Consulting
site_logo: /img/logo.png
site_email: info@acosysconsulting.com
site_tel: (514) 888-8888
site_description: >-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet
  iaculis elit. Nam semper ut arcu non placerat. Praesent nibh massa varius.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet
  iaculis elit. Nam semper ut arcu non placerat. Praesent nibh massa varius.
url_facebook: 'https://facebook.com'
url_linkedin: 'https://linkedin.com'
