site_title: Acosys Consulting
site_logo: /img/logo.jpg
site_email: info@acosysconsulting.com
site_tel: (514) 744-9433 ext. 118
url_facebook: 'https://facebook.com'
url_linkedin: 'https://linkedin.com'
