site_title: Acosys Consulting Services
site_logo: /img/logo.jpg
site_email: info@acosysconsulting.com
site_tel: (514) 744-9433 ext. 118
url_facebook: 'https://www.facebook.com/Acosys-Consulting-Services-Inc-381883495213184/'
url_twitter: 'https://twitter.com/acosysservices'
url_linkedin: 'https://www.linkedin.com/company/acosys-consulting-service-inc./'
